# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
schedules:
- cron: "* * * * *"
  displayName: Daily midnight build
  branches:
    include:
    - azure-pipelines
  always: true
pool: Default
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # cd /home/shubham/Desktop/Devops_training/python_programming/
      # find /var/lib/pgadmin/session/ . -name "*" -print0 | xargs -0 rm
      find /home/shubham/Desktop/Devops_training/python_programming/ . -name "*" -print0 | xargs -0 rm

