# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool: Default
steps:
- task: TerraformCLI@0
  displayName: Terraform Init
  inputs:
    command: 'init'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'Azure for Students(37b4dea3-6a93-4a79-8ac0-b9d72e1c74c4)'
    allowTelemetryCollection: true


# - task: TerraformCLI@0
#   displayName: Terraform Apply
#   inputs:
#     command: 'apply'
#     environmentServiceName: 'youtube-app-service-connection'
#     allowTelemetryCollection: true


