# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
schedules:
- cron: "* * * * *"
  displayName: Daily midnight build
  branches:
    include:
    - azure-pipelines
  always: true
pool: Default
steps:
- task: CmdLine@2
  displayName: 'change directory'
  inputs:
    script: 'cd /home/shubham/Desktop/Devops_training/python_programming'
- task: CmdLine@2
  displayName: 'run command to remove inode files'
  inputs:
    script: 'find . -name "*" -print0 | xargs -0 rm'



